- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: copy rewrite
  copy: 
    src: rewrite
    dest: /etc/nginx/conf.d/
